#!/usr/bin/env zsh

print_header() {
  printf "\e[34m"
  echo '----------------------------------------------------------------------'
  echo '                               ______                                 '
  echo '                              /\  == \                                '
  echo '                              \ \  _-/                                '
  echo '                               \ \_\                                  '
  echo '                                \/_/                                  '
  echo '                                                                      '
  echo '                          RPID PROTOTYPING                            '
  echo '                                                                      '
  echo '----------------------------------------------------------------------'
  printf "\e[0m\n"
}

install_modules() {
  echo 'Installing modules...'
  npm i -D autoprefixer babel-core babel-eslint babel-loader babel-preset-es2015 \
    babel-preset-react babel-preset-stage-2 css-loader css-mqpacker eslint \
    eslint-loader eslint-plugin-babel eslint-plugin-react file-loader \
    image-webpack-loader jade json-server postcss-loader style-loader stylint \
    stylint-loader stylint-stylish stylus stylus-loader url-loader webpack \
    webpack-dev-server
  npm i -S babel-polyfill history mirror-key-value react react-dom react-router \
    sugarshin/fetch#84b2b2328d58252df63ce31f747e51c4b7e8742b
}

rms() {
  echo 'Ready...'
  rm -rf .git bootstrap
}

main() {
  print_header

  install_modules

  rms

  echo 'Done !!!!'
}

main
