#!/usr/bin/env zsh

print_header() {
  printf "\e[34m"
  echo '----------------------------------------------------------'
  echo '                        ______                            '
  echo '                       /\  == \                           '
  echo '                       \ \  _-/                           '
  echo '                        \ \_\                             '
  echo '                         \/_/                             '
  echo '                                                          '
  echo '                    RPID PROTOTYPING                      '
  echo '                                                          '
  echo '----------------------------------------------------------'
  printf "\e[0m\n"
}

install_modules() {
  echo 'Installing modules...'
  npm i -D autoprefixer babel-core babel-eslint babel-loader babel-preset-es2015 \
    babel-preset-react babel-preset-stage-2 css-loader css-mqpacker eslint \
    eslint-loader eslint-plugin-babel eslint-plugin-react jade json-server \
    postcss-loader style-loader stylint stylint-loader stylint-stylish \
    stylus-loader webpack webpack-dev-server
  npm i -S babel-polyfill es6-promise react react-dom whatwg-fetch
}

rms() {
  echo 'Ready...'
  rm -rf .git bootstrap
}

main() {
  print_header

  install_modules

  rms

  echo 'Done !!!!'
}

main
